export const sample_products: any[] = [
  {
    id: "1",
    name: "Python Notebook",
    tags: ["Python", "Notebook", "Stationery"],
    color: "Yellow",
    description: "A notebook with a Python theme.",
    price: 50,
    imageurl: "assets/PyNote.jpg",
  },
  {
    id: "2",
    name: "JavaScript Mug",
    tags: ["JavaScript", "Mug", "Drinkware"],
    color: "Blue",
    description: "A mug with a JavaScript theme.",
    price: 30,
    imageurl: "assets/JaMug.jpg",
  },
  {
    id: "3",
    name: "HTML5 T-Shirt",
    tags: ["HTML5", "T-Shirt", "Clothing"],
    color: "White",
    description: "A T-Shirt with a HTML5 theme.",
    price: 20,
    imageurl: "assets/HTML5T.jpg",
  },
  {
    id: "4",
    name: "CSS3 T-Shirt",
    tags: ["CSS3", "T-Shirt", "Clothing"],
    color: "White",
    description: "A T-Shirt with a CSS3 theme.",
    price: 20,
    imageurl: "assets/CSS3T.jpg",
  },
  {
    id: "5",
    name: "Java Bag",
    tags: ["Java", "Totebag", "Bags"],
    color: "Black",
    description: "A backpack with a Java theme.",
    price: 100,
    imageurl: "assets/JavaB.jpg",
  },
  {
    id: "6",
    name: "Swift Water Bottle",
    tags: ["Swift", "Water Bottle", "Drinkware"],
    color: "White",
    description: "A water bottle with a Swift theme.",
    price: 40,
    imageurl: "assets/SwiftWB.jpg",
  },
  {
    id: "7",
    name: "Rust Keychain",
    tags: ["Rust", "Keychain", "Accessories"],
    color: "Silver",
    description: "A keychain with a Rust theme.",
    price: 10,
    imageurl: "assets/RustK.jpg",
  },
  {
    id: "8",
    name: "Scala Sticker",
    tags: ["Scala", "Sticker", "Stationery"],
    color: "White",
    description: "A sticker with a Scala theme.",
    price: 5,
    imageurl: "assets/ScalaS.jpg",
  },
  {
    id: "9",
    name: "Assembly T-shirt",
    tags: ["Perl", "T-Shirt", "Clothing"],
    color: "White",
    description: "A pen with a Perl theme.",
    price: 10,
    imageurl: "assets/AssemblyT.jpg",
  },
  {
    id: "10",
    name: "MATLAB T-Shirt",
    tags: ["MATLAB", "T-Shirt", "Clothing"],
    color: "White",
    description: "A T-Shirt with a MATLAB theme.",
    price: 20,
    imageurl: "assets/MATLABT.jpg",
  },
  {
    id: "11",
    name: "C++ Mug",
    tags: ["C++", "Mug", "Drinkware"],
    color: "White",
    description: "A mug with a C++ theme.",
    price: 30,
    imageurl: "assets/C++M.jpg",
  },
  {
    id: "12",
    name: "C# Sticker",
    tags: ["C#", "Sticker", "Stationery"],
    color: "Black",
    description: "A sticker with a C# theme.",
    price: 50,
    imageurl: "assets/CsS.jpg",
  },
  {
    id: "13",
    name: "C Mug",
    tags: ["C", "Mug", "Drinkware"],
    color: "White",
    description: "A mug with a C theme.",
    price: 30,
    imageurl: "assets/CM.jpg",
  },
  {
    id: "14",
    name: "C++ Keychain",
    tags: ["C++", "Keychain", "Accessories"],
    color: "Gold",
    description: "A keychain with a C++ theme.",
    price: 10,
    imageurl: "assets/C++K.jpg",
  },
  {
    id: "15",
    name: "C# Mug",
    tags: ["C#", "Mug", "Drinkware"],
    color: "White",
    description: "A mug with a C# theme.",
    price: 30,
    imageurl: "assets/CsM.jpg",
  },
  {
    id: "16",
    name: "C Sticker",
    tags: ["C", "Sticker", "Stationery"],
    color: "White",
    description: "A sticker with a C theme.",
    price: 5,
    imageurl: "assets/CS.jpg",
  },
  {
    id: "17",
    name: "C++ T-Shirt",
    tags: ["C++", "T-Shirt", "Clothing"],
    color: "White",
    description: "A T-Shirt with a C++ theme.",
    price: 20,
    imageurl: "assets/C++T.jpg",
  },
  {
    id: "18",
    name: "C# T-Shirt",
    tags: ["C#", "T-Shirt", "Clothing"],
    color: "White",
    description: "A T-Shirt with a C# theme.",
    price: 20,
    imageurl: "assets/CsT.jpg",
  },
];
export const sample_users: any[] = [
  {
    name: "Pan",
    email: "vlastospan@gmail.com",
    password: "1234",
    address: "Athens",
    isAdmin: true,
  },
  {
    name: "Tan",
    email: "vlastostan@gmail.com",
    password: "1234",
    address: "Athens",
    isAdmin: false,
  },
];
